"""Hand-written PostgreSQL translation for every Oracle template.

This is the gold standard the model is trained towards, and the thing every
baseline is measured against. One translation per Oracle template, written
against the same anchor names, so the 123 entries here render out to the whole
pair set automatically.

Why hand-written rather than generated by `sqlglot`: sqlglot is one of the
*baselines* this project measures itself against. Using its output as the
training target would mean fine-tuning a model to imitate the thing it is
being compared to, and the result could never beat it. The comparison in the
README is only meaningful if the gold is independent of the baseline.

Each translation is still verified by execution against PostgreSQL and compared
to Oracle's result. Being hand-written buys no trust here; nothing is accepted
on the basis that a human typed it.

`param_translate` rewrites a parameter value for the PostgreSQL side, for cases
where the same parameter means something different in each dialect — Oracle's
`TRUNC(d, 'MM')` against PostgreSQL's `DATE_TRUNC('month', d)`, for example.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True, slots=True)
class Translation:
    """The PostgreSQL counterpart of one Oracle template."""

    sql: str
    param_translate: dict[str, dict[str, str]] = field(default_factory=dict)
    note: str | None = None
    """Why the translation is non-obvious, where that is worth recording."""


def _x(sql: str, **kwargs: object) -> Translation:
    return Translation(sql=" ".join(sql.split()), **kwargs)  # type: ignore[arg-type]


# --------------------------------------------------------------------------- #
# Shared SQL fragments
#
# Both of these reproduce Oracle behaviour that was measured rather than
# assumed, after a first attempt got them wrong:
#
#   ADD_MONTHS maps the last day of a month onto the last day of the target
#   month, so 2024-06-30 + 1 month is 2024-07-31, not 2024-07-30. PostgreSQL's
#   interval arithmetic gives the latter, so the end-of-month case is special
#   cased. The ordinary case already agrees, including clamping 2024-01-31 + 1
#   month to 2024-02-29.
#
#   MONTHS_BETWEEN returns a whole number, ignoring the time of day, when the
#   two days-of-month are equal or both dates are the last day of their month.
#   Otherwise it adds a fraction on a 31-day basis that does include the time.
# --------------------------------------------------------------------------- #

_IS_MONTH_END = (
    "CAST({col} AS date) = CAST(DATE_TRUNC('month', {col})"
    " + INTERVAL '1 month' - INTERVAL '1 day' AS date)"
)

_TIME_OF_DAY = "({col} - DATE_TRUNC('day', {col}))"

ADD_MONTHS_SQL = (
    "CASE WHEN " + _IS_MONTH_END.format(col="{fact_date}") + " THEN"
    " DATE_TRUNC('month', {fact_date} + ({m} * INTERVAL '1 month'))"
    " + INTERVAL '1 month' - INTERVAL '1 day' + "
    + _TIME_OF_DAY.format(col="{fact_date}")
    + " ELSE {fact_date} + ({m} * INTERVAL '1 month') END"
)

_WHOLE_MONTHS = (
    "((EXTRACT(YEAR FROM {fact_date2}) - EXTRACT(YEAR FROM {fact_date})) * 12"
    " + (EXTRACT(MONTH FROM {fact_date2}) - EXTRACT(MONTH FROM {fact_date})))"
)

_DAY_AND_TIME_FRACTION = (
    "((EXTRACT(DAY FROM {fact_date2}) - EXTRACT(DAY FROM {fact_date})"
    " + (EXTRACT(HOUR FROM {fact_date2}) * 3600 + EXTRACT(MINUTE FROM {fact_date2}) * 60"
    " + EXTRACT(SECOND FROM {fact_date2})"
    " - EXTRACT(HOUR FROM {fact_date}) * 3600 - EXTRACT(MINUTE FROM {fact_date}) * 60"
    " - EXTRACT(SECOND FROM {fact_date})) / 86400.0) / 31.0)"
)

MONTHS_BETWEEN_SQL = (
    "CASE WHEN EXTRACT(DAY FROM {fact_date2}) = EXTRACT(DAY FROM {fact_date})"
    " OR ("
    + _IS_MONTH_END.format(col="{fact_date2}")
    + " AND "
    + _IS_MONTH_END.format(col="{fact_date}")
    + ")"
    " THEN " + _WHOLE_MONTHS + " ELSE " + _WHOLE_MONTHS + " + " + _DAY_AND_TIME_FRACTION + " END"
)


TRANSLATIONS: dict[str, Translation] = {
    # ----------------------------------------------------------------- rownum
    "rownum_inline": _x(
        "SELECT {fact_pk} FROM {fact} LIMIT {n}",
        note="ROWNUM without ORDER BY picks an arbitrary subset in both engines.",
    ),
    "rownum_ordered_subquery": _x(
        """SELECT * FROM (SELECT {dim_pk}, {dim_text} FROM {dim} ORDER BY {dim_pk}) q
           LIMIT {n}""",
        note="PostgreSQL requires an alias on a subquery in FROM.",
    ),
    "rownum_as_column": _x("SELECT ROW_NUMBER() OVER () AS rn, {fact_pk} FROM {fact} LIMIT {n}"),
    "rownum_pagination": _x(
        """SELECT rn, {fact_pk} FROM
             (SELECT a.{fact_pk}, ROW_NUMBER() OVER () AS rn FROM
                (SELECT {fact_pk} FROM {fact} ORDER BY {fact_pk}) a
              LIMIT 20) q
           WHERE rn > 10"""
    ),
    "rownum_with_filter": _x(
        "SELECT {fact_pk}, {fact_date} FROM {fact} WHERE {fact_date} IS NOT NULL LIMIT {n}"
    ),
    # ------------------------------------------------------------ fetch first
    "fetch_first_basic": _x(
        "SELECT {dim_pk}, {dim_text} FROM {dim} ORDER BY {dim_pk} FETCH FIRST {n} ROWS ONLY"
    ),
    "fetch_first_desc": _x(
        "SELECT {fact_pk} FROM {fact} ORDER BY {fact_date} DESC FETCH FIRST {n} ROWS ONLY"
    ),
    "fetch_offset": _x(
        """SELECT {fact_pk} FROM {fact} ORDER BY {fact_pk}
           OFFSET {k} ROWS FETCH NEXT {n} ROWS ONLY"""
    ),
    "fetch_with_ties": _x(
        """SELECT {fact_pk}, {fact_date} FROM {fact}
           ORDER BY {fact_date} FETCH FIRST {n} ROWS WITH TIES"""
    ),
    "fetch_percent": _x(
        """SELECT {fact_pk} FROM {fact} ORDER BY {fact_pk}
           LIMIT (SELECT CEIL(COUNT(*) * 0.05) FROM {fact})""",
        note="PostgreSQL has no PERCENT clause; the count is computed instead.",
    ),
    # -------------------------------------------------------------------- nvl
    "nvl_numeric": _x(
        "SELECT {fact_pk}, COALESCE({fact_num_nullable}, 0) AS v FROM {fact} ORDER BY {fact_pk}"
    ),
    "nvl_dim_numeric": _x(
        "SELECT {dim_pk}, COALESCE({dim_num_nullable}, {d}) AS v FROM {dim} ORDER BY {dim_pk}"
    ),
    "nvl_text": _x(
        """SELECT {dim_pk}, COALESCE({dim_text_nullable}, 'UNKNOWN') AS v
           FROM {dim} ORDER BY {dim_pk}"""
    ),
    "nvl_in_where": _x("SELECT COUNT(*) FROM {fact} WHERE COALESCE({fact_num_nullable}, 0) > 0"),
    "nvl_in_aggregate": _x("SELECT SUM(COALESCE({fact_num_nullable}, 0)) AS total FROM {fact}"),
    "nvl2_numeric": _x(
        """SELECT {fact_pk},
                  CASE WHEN {fact_num_nullable} IS NOT NULL THEN 'has_value' ELSE 'missing' END AS v
           FROM {fact} ORDER BY {fact_pk}""",
        note="NVL2(a, b, c) becomes CASE WHEN a IS NOT NULL THEN b ELSE c END.",
    ),
    "nvl2_date": _x(
        """SELECT {fact_pk},
                  CASE WHEN {fact_date2} IS NOT NULL THEN 'closed' ELSE 'open' END AS state
           FROM {fact} ORDER BY {fact_pk}"""
    ),
    "coalesce_two": _x(
        "SELECT {fact_pk}, COALESCE({fact_num_nullable}, 0) AS v FROM {fact} ORDER BY {fact_pk}"
    ),
    "nullif_basic": _x(
        "SELECT {fact_pk}, NULLIF({fact_num_nullable}, 0) AS v FROM {fact} ORDER BY {fact_pk}"
    ),
    # ----------------------------------------------------------------- decode
    "decode_two_branch": _x(
        """SELECT {fact_pk},
                  CASE WHEN {fact_status} = '{fact_status_value}' THEN 1 ELSE 0 END AS flag
           FROM {fact} ORDER BY {fact_pk}""",
        note="DECODE is Oracle-only; CASE is the portable equivalent.",
    ),
    "decode_with_default": _x(
        """SELECT {fact_pk},
                  CASE WHEN {fact_status} = '{fact_status_value}' THEN 'match'
                       ELSE 'other' END AS label
           FROM {fact} ORDER BY {fact_pk}"""
    ),
    "decode_aggregate": _x(
        """SELECT SUM(CASE WHEN {fact_status} = '{fact_status_value}' THEN 1 ELSE 0 END) AS matched,
                  COUNT(*) AS total
           FROM {fact}"""
    ),
    "decode_dim": _x(
        """SELECT {dim_pk},
                  CASE WHEN {dim_status} = '{dim_status_value}' THEN 'Y' ELSE 'N' END AS flag
           FROM {dim} ORDER BY {dim_pk}"""
    ),
    "case_equivalent": _x(
        """SELECT {fact_pk},
                  CASE WHEN {fact_status} = '{fact_status_value}' THEN 1 ELSE 0 END AS flag
           FROM {fact} ORDER BY {fact_pk}"""
    ),
    # ----------------------------------------------------------- null concat
    "concat_nullable_text": _x(
        """SELECT {dim_pk}, {dim_text} || '-' || COALESCE({dim_text_nullable}, '') AS v
           FROM {dim} ORDER BY {dim_pk}""",
        note="Oracle treats NULL as empty when concatenating; PostgreSQL propagates it.",
    ),
    "concat_fact_nullable": _x(
        """SELECT {fact_pk}, COALESCE({fact_text_nullable}, '') || '!' AS v
           FROM {fact} ORDER BY {fact_pk}""",
        note="Without COALESCE the whole expression would be NULL in PostgreSQL.",
    ),
    "concat_guarded": _x(
        """SELECT {dim_pk}, {dim_text} || COALESCE({dim_text_nullable}, '') AS v
           FROM {dim} ORDER BY {dim_pk}""",
        note="NVL(x, '') is NULL in Oracle because '' is NULL, so this happens to agree.",
    ),
    "null_text_count": _x("SELECT COUNT(*) AS n FROM {dim} WHERE {dim_text_nullable} IS NULL"),
    "concat_function": _x(
        "SELECT {dim_pk}, CONCAT({dim_text}, '_x') AS v FROM {dim} ORDER BY {dim_pk}"
    ),
    # ------------------------------------------------------------ outer joins
    "plus_left_outer": _x(
        """SELECT d.{dim_pk}, f.{fact_pk}
           FROM {dim} d LEFT JOIN {fact} f ON d.{dim_pk} = f.{fact_fk}
           ORDER BY d.{dim_pk}, f.{fact_pk}""",
        note="(+) marks the optional side, so f(+) becomes a LEFT JOIN from d.",
    ),
    "plus_right_outer": _x(
        """SELECT f.{fact_pk}, d.{dim_pk}
           FROM {fact} f LEFT JOIN {dim} d ON f.{fact_fk} = d.{dim_pk}
           ORDER BY f.{fact_pk}"""
    ),
    "plus_with_filter": _x(
        """SELECT d.{dim_pk}, COUNT(f.{fact_pk}) AS n
           FROM {dim} d LEFT JOIN {fact} f ON d.{dim_pk} = f.{fact_fk}
           GROUP BY d.{dim_pk} ORDER BY d.{dim_pk}"""
    ),
    "ansi_left_join": _x(
        """SELECT d.{dim_pk}, COUNT(f.{fact_pk}) AS n
           FROM {dim} d LEFT JOIN {fact} f ON d.{dim_pk} = f.{fact_fk}
           GROUP BY d.{dim_pk} ORDER BY d.{dim_pk}"""
    ),
    # ------------------------------------------------------------- connect by
    "connect_by_level": _x(
        """WITH RECURSIVE t AS (
               SELECT {hier_pk}, {hier_label}, 1 AS lvl
               FROM {hier} WHERE {hier_parent} IS NULL
               UNION ALL
               SELECT c.{hier_pk}, c.{hier_label}, p.lvl + 1
               FROM {hier} c JOIN t p ON c.{hier_parent} = p.{hier_pk}
           )
           SELECT {hier_pk}, {hier_label}, lvl FROM t ORDER BY {hier_pk}""",
        note="CONNECT BY becomes WITH RECURSIVE; LEVEL becomes a counter column.",
    ),
    "connect_by_path": _x(
        """WITH RECURSIVE t AS (
               SELECT {hier_pk}, '/' || {hier_label} AS path
               FROM {hier} WHERE {hier_parent} IS NULL
               UNION ALL
               SELECT c.{hier_pk}, p.path || '/' || c.{hier_label}
               FROM {hier} c JOIN t p ON c.{hier_parent} = p.{hier_pk}
           )
           SELECT {hier_pk}, path FROM t ORDER BY {hier_pk}""",
        note="SYS_CONNECT_BY_PATH is built up by concatenation in the recursive step.",
    ),
    "connect_by_root": _x(
        """WITH RECURSIVE t AS (
               SELECT {hier_pk}, {hier_label} AS root_label
               FROM {hier} WHERE {hier_parent} IS NULL
               UNION ALL
               SELECT c.{hier_pk}, p.root_label
               FROM {hier} c JOIN t p ON c.{hier_parent} = p.{hier_pk}
           )
           SELECT {hier_pk}, root_label FROM t ORDER BY {hier_pk}""",
        note="CONNECT_BY_ROOT is carried down unchanged through the recursion.",
    ),
    "connect_by_isleaf": _x(
        """WITH RECURSIVE t AS (
               SELECT {hier_pk} FROM {hier} WHERE {hier_parent} IS NULL
               UNION ALL
               SELECT c.{hier_pk} FROM {hier} c JOIN t p ON c.{hier_parent} = p.{hier_pk}
           )
           SELECT t.{hier_pk},
                  CASE WHEN EXISTS (SELECT 1 FROM {hier} x
                                    WHERE x.{hier_parent} = t.{hier_pk})
                       THEN 0 ELSE 1 END AS is_leaf
           FROM t ORDER BY t.{hier_pk}""",
        note="CONNECT_BY_ISLEAF becomes an EXISTS check for children.",
    ),
    "connect_by_depth_filter": _x(
        """WITH RECURSIVE t AS (
               SELECT {hier_pk}, 1 AS lvl FROM {hier} WHERE {hier_parent} IS NULL
               UNION ALL
               SELECT c.{hier_pk}, p.lvl + 1
               FROM {hier} c JOIN t p ON c.{hier_parent} = p.{hier_pk}
               WHERE p.lvl + 1 <= 2
           )
           SELECT {hier_pk}, lvl FROM t ORDER BY {hier_pk}"""
    ),
    "connect_by_order_siblings": _x(
        """WITH RECURSIVE t AS (
               SELECT {hier_pk}, 1 AS lvl, ARRAY[{hier_pk}] AS sort_path
               FROM {hier} WHERE {hier_parent} IS NULL
               UNION ALL
               SELECT c.{hier_pk}, p.lvl + 1, p.sort_path || c.{hier_pk}
               FROM {hier} c JOIN t p ON c.{hier_parent} = p.{hier_pk}
           )
           SELECT {hier_pk}, lvl FROM t ORDER BY sort_path""",
        note="ORDER SIBLINGS BY needs an explicit materialised path to sort on.",
    ),
    # ---------------------------------------------------------------- sysdate
    "sysdate_filter_count": _x(
        "SELECT COUNT(*) AS n FROM {fact} WHERE {fact_date} < LOCALTIMESTAMP",
        note="SYSDATE is the server's local time with no zone, which is LOCALTIMESTAMP.",
    ),
    "sysdate_trunc": _x("SELECT DATE_TRUNC('day', LOCALTIMESTAMP) AS today"),
    "sysdate_window": _x(
        """SELECT COUNT(*) AS n FROM {fact}
           WHERE {fact_date} BETWEEN LOCALTIMESTAMP - ({m} * INTERVAL '1 month')
                                 AND LOCALTIMESTAMP"""
    ),
    "sysdate_comparison_flag": _x(
        """SELECT {fact_pk}, CASE WHEN {fact_date} > LOCALTIMESTAMP THEN 1 ELSE 0 END AS future
           FROM {fact} ORDER BY {fact_pk}"""
    ),
    # ----------------------------------------------------------- to_char/date
    "to_char_date_iso": _x(
        "SELECT {fact_pk}, TO_CHAR({fact_date}, '{mask}') AS d FROM {fact} ORDER BY {fact_pk}",
        note="These numeric format masks mean the same thing in both engines.",
    ),
    "to_char_date_part": _x(
        """SELECT TO_CHAR({fact_date}, '{part}') AS p, COUNT(*) AS n FROM {fact}
           GROUP BY TO_CHAR({fact_date}, '{part}') ORDER BY p"""
    ),
    "to_date_literal": _x(
        "SELECT CAST(TO_DATE('{d}', 'YYYY-MM-DD') AS timestamp(0)) AS parsed",
        note="Oracle TO_DATE yields a DATE, which carries a time; PostgreSQL's yields a date.",
    ),
    "to_date_filter": _x(
        """SELECT COUNT(*) AS n FROM {fact}
           WHERE {fact_date} >= TO_DATE('2025-01-01', 'YYYY-MM-DD')"""
    ),
    "extract_from_date": _x(
        """SELECT EXTRACT(YEAR FROM {fact_date}) AS y, COUNT(*) AS n FROM {fact}
           GROUP BY EXTRACT(YEAR FROM {fact_date}) ORDER BY y"""
    ),
    # ------------------------------------------------------------- add_months
    "add_months_basic": _x(
        "SELECT {fact_pk}, " + ADD_MONTHS_SQL + " AS shifted FROM {fact} ORDER BY {fact_pk}",
        note="Oracle maps the last day of a month onto the last day of the target "
        "month, which PostgreSQL interval arithmetic does not.",
    ),
    "months_between_cols": _x(
        "SELECT {fact_pk}, " + MONTHS_BETWEEN_SQL + " AS gap FROM {fact} ORDER BY {fact_pk}",
        note="MONTHS_BETWEEN has no PostgreSQL equivalent. The whole-number special "
        "cases and Oracle's 31-day fractional basis are both reproduced.",
    ),
    "months_between_rounded": _x(
        "SELECT {fact_pk}, ROUND(" + MONTHS_BETWEEN_SQL + ", 2) AS gap "
        "FROM {fact} WHERE {fact_date2} IS NOT NULL ORDER BY {fact_pk}",
    ),
    "last_day_basic": _x(
        """SELECT {fact_pk},
                  DATE_TRUNC('month', {fact_date}) + INTERVAL '1 month' - INTERVAL '1 day'
                  + ({fact_date} - DATE_TRUNC('day', {fact_date})) AS eom
           FROM {fact} ORDER BY {fact_pk}""",
        note="Oracle LAST_DAY keeps the time of day, so it is added back here.",
    ),
    "add_months_filter": _x(
        """SELECT COUNT(*) AS n FROM {fact}
           WHERE {fact_date} < CAST(TO_DATE('2026-01-01', 'YYYY-MM-DD') AS timestamp(0))
                               - ({m} * INTERVAL '1 month')""",
        note="The first of the month is never a month end, so the simple form is exact.",
    ),
    # ------------------------------------------------------------- trunc date
    "trunc_date_day": _x(
        "SELECT {fact_pk}, DATE_TRUNC('day', {fact_date}) AS d FROM {fact} ORDER BY {fact_pk}"
    ),
    "trunc_date_unit": _x(
        "SELECT {fact_pk}, DATE_TRUNC('{unit}', {fact_date}) AS d FROM {fact} ORDER BY {fact_pk}",
        param_translate={
            "unit": {
                "MM": "month",
                "YYYY": "year",
                "IW": "week",
                "HH": "hour",
                "DD": "day",
                "Q": "quarter",
                "MI": "minute",
            }
        },
        note="Oracle's TRUNC format codes map onto DATE_TRUNC's unit names.",
    ),
    "trunc_date_group": _x(
        """SELECT DATE_TRUNC('month', {fact_date}) AS month, COUNT(*) AS n FROM {fact}
           GROUP BY DATE_TRUNC('month', {fact_date}) ORDER BY month"""
    ),
    "date_difference_days": _x(
        """SELECT {fact_pk},
                  CAST({fact_date2} AS date) - CAST({fact_date} AS date) AS days
           FROM {fact} WHERE {fact_date2} IS NOT NULL ORDER BY {fact_pk}""",
        note="Subtracting two dates gives an integer day count in PostgreSQL.",
    ),
    # ------------------------------------------------------------------- dual
    "dual_literal": _x("SELECT {v} AS v", note="PostgreSQL needs no FROM clause."),
    "dual_integer_division": _x(
        "SELECT 7::numeric/2 AS v",
        note="The important one: PostgreSQL does integer division and truncates, "
        "so 7/2 would be 3. Oracle's NUMBER has no integer type.",
    ),
    "dual_string_length": _x("SELECT LENGTH('abcdef') AS v"),
    "dual_null_concat": _x(
        "SELECT CONCAT('a', NULL) AS v",
        note="|| propagates NULL in PostgreSQL; CONCAT treats it as empty, as Oracle does.",
    ),
    "dual_arithmetic": _x("SELECT MOD(17, 5) AS m, ABS(-3) AS a, CEIL(2.1) AS c"),
    "dual_greatest": _x("SELECT GREATEST(1, 7, 3) AS g, LEAST(1, 7, 3) AS l"),
    # ------------------------------------------------------------------ minus
    "minus_basic": _x(
        "SELECT {dim_pk} FROM {dim} EXCEPT SELECT {fact_fk} FROM {fact}",
        note="MINUS is spelled EXCEPT everywhere else.",
    ),
    "minus_reversed": _x(
        """SELECT {fact_fk} FROM {fact} WHERE {fact_fk} IS NOT NULL
           EXCEPT
           SELECT {dim_pk} FROM {dim} WHERE {dim_pk} > 0"""
    ),
    "intersect_basic": _x(
        """SELECT {fact_fk} FROM {fact} WHERE {fact_fk} IS NOT NULL
           INTERSECT
           SELECT {dim_pk} FROM {dim}"""
    ),
    "union_all_basic": _x(
        """(SELECT {fact_pk} AS k FROM {fact} LIMIT 5)
           UNION ALL
           (SELECT {dim_pk} AS k FROM {dim} LIMIT 5)""",
        note="A LIMIT inside a set operation branch must be parenthesised.",
    ),
    # ---------------------------------------------------------------- listagg
    "listagg_basic": _x(
        """SELECT {sum_fk},
                  STRING_AGG(
                    REGEXP_REPLACE(
                      CASE WHEN {sum_num}::text LIKE '%.%'
                           THEN RTRIM(RTRIM({sum_num}::text, '0'), '.')
                           ELSE {sum_num}::text END,
                      '^(-?)0\\.', '\\1.'),
                    ',' ORDER BY {sum_num}) AS vals
           FROM {sum_table} GROUP BY {sum_fk} ORDER BY {sum_fk}""",
        note="LISTAGG becomes STRING_AGG, but Oracle's default TO_CHAR(number) drops "
        "trailing zeros and the leading zero before the decimal point, which has to "
        "be reproduced.",
    ),
    "listagg_distinct": _x(
        """SELECT {fact_status},
                  STRING_AGG(DISTINCT {fact_pk}::text, ';' ORDER BY {fact_pk}::text) AS ids
           FROM {fact} GROUP BY {fact_status} ORDER BY {fact_status}"""
    ),
    "listagg_over_all": _x(
        """SELECT STRING_AGG({dim_pk}::text, '|' ORDER BY {dim_pk}) AS all_ids
           FROM (SELECT {dim_pk} FROM {dim} LIMIT 10) q"""
    ),
    # ------------------------------------------------------------------ pivot
    "pivot_status_counts": _x(
        "SELECT {pivot_agg} FROM {fact}",
        note="PostgreSQL has no PIVOT; conditional aggregation gives the same shape.",
    ),
    "unpivot_basic": _x(
        """SELECT {fact_pk}, 'D1' AS which, {fact_date} AS val
           FROM (SELECT {fact_pk}, {fact_date} FROM {fact} LIMIT 5) q
           UNION ALL
           SELECT {fact_pk}, 'D2' AS which, {fact_date} AS val
           FROM (SELECT {fact_pk}, {fact_date} FROM {fact} LIMIT 5) q2""",
        note="UNPIVOT is rewritten as a UNION ALL, one branch per source column.",
    ),
    # --------------------------------------------------------------- sequence
    "sequence_nextval": _x(
        "SELECT NEXTVAL('{seq}') AS v",
        note="A pseudo-column in Oracle, a function in PostgreSQL.",
    ),
    "sequence_nextval_expr": _x("SELECT NEXTVAL('{seq}') + 0 AS v"),
    # --------------------------------------------------------------- analytic
    "analytic_row_number": _x(
        """SELECT {fact_pk}, {fact_fk},
                  ROW_NUMBER() OVER (PARTITION BY {fact_fk} ORDER BY {fact_pk}) AS rn
           FROM {fact} ORDER BY {fact_pk}""",
        note="Window functions are standard SQL and need no translation.",
    ),
    "analytic_rank": _x(
        """SELECT {fact_pk}, RANK() OVER (ORDER BY {fact_date}) AS rnk,
                  DENSE_RANK() OVER (ORDER BY {fact_date}) AS drnk
           FROM {fact} ORDER BY {fact_pk}"""
    ),
    "analytic_lag_lead": _x(
        """SELECT {fact_pk},
                  LAG({fact_date}) OVER (ORDER BY {fact_pk}) AS prev_d,
                  LEAD({fact_date}) OVER (ORDER BY {fact_pk}) AS next_d
           FROM {fact} ORDER BY {fact_pk}"""
    ),
    "analytic_running_sum": _x(
        """SELECT {sum_fk}, {sum_num},
                  SUM({sum_num}) OVER (PARTITION BY {sum_fk} ORDER BY {sum_num}
                                       ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running
           FROM {sum_table} ORDER BY {sum_fk}, {sum_num}"""
    ),
    "analytic_ntile": _x(
        """SELECT {fact_pk}, NTILE(4) OVER (ORDER BY {fact_pk}) AS quartile
           FROM {fact} ORDER BY {fact_pk}"""
    ),
    "analytic_first_last_value": _x(
        """SELECT {sum_fk},
                  FIRST_VALUE({sum_num}) OVER (PARTITION BY {sum_fk} ORDER BY {sum_num}) AS lo,
                  LAST_VALUE({sum_num}) OVER (PARTITION BY {sum_fk} ORDER BY {sum_num}
                      ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS hi
           FROM {sum_table} ORDER BY {sum_fk}, {sum_num}"""
    ),
    "analytic_count_over": _x(
        """SELECT {fact_pk}, COUNT(*) OVER (PARTITION BY {fact_fk}) AS peers
           FROM {fact} ORDER BY {fact_pk}"""
    ),
    # --------------------------------------------------------------- subquery
    "subquery_in": _x(
        """SELECT {fact_pk} FROM {fact}
           WHERE {fact_fk} IN (SELECT {dim_pk} FROM {dim} WHERE {dim_pk} > 0)
           ORDER BY {fact_pk}"""
    ),
    "subquery_exists": _x(
        """SELECT d.{dim_pk} FROM {dim} d
           WHERE EXISTS (SELECT 1 FROM {fact} f WHERE f.{fact_fk} = d.{dim_pk})
           ORDER BY d.{dim_pk}"""
    ),
    "subquery_not_exists": _x(
        """SELECT d.{dim_pk} FROM {dim} d
           WHERE NOT EXISTS (SELECT 1 FROM {fact} f WHERE f.{fact_fk} = d.{dim_pk})
           ORDER BY d.{dim_pk}"""
    ),
    "subquery_scalar": _x(
        """SELECT d.{dim_pk},
                  (SELECT COUNT(*) FROM {fact} f WHERE f.{fact_fk} = d.{dim_pk}) AS n
           FROM {dim} d ORDER BY d.{dim_pk}"""
    ),
    "subquery_inline_view": _x(
        """SELECT x.{fact_fk}, x.n FROM
             (SELECT {fact_fk}, COUNT(*) AS n FROM {fact} GROUP BY {fact_fk}) x
           WHERE x.n > 1 ORDER BY x.{fact_fk}"""
    ),
    # -------------------------------------------------------------------- cte
    "cte_single": _x(
        """WITH counts AS (SELECT {fact_fk} AS k, COUNT(*) AS n FROM {fact} GROUP BY {fact_fk})
           SELECT k, n FROM counts WHERE n > 1 ORDER BY k"""
    ),
    "cte_two": _x(
        """WITH a AS (SELECT {fact_fk} AS k, COUNT(*) AS n FROM {fact} GROUP BY {fact_fk}),
                b AS (SELECT k, n FROM a WHERE n >= 2)
           SELECT k, n FROM b ORDER BY k"""
    ),
    "cte_joined": _x(
        """WITH agg AS (SELECT {fact_fk} AS k, COUNT(*) AS n FROM {fact} GROUP BY {fact_fk})
           SELECT d.{dim_pk}, COALESCE(agg.n, 0) AS n
           FROM {dim} d LEFT JOIN agg ON agg.k = d.{dim_pk}
           ORDER BY d.{dim_pk}"""
    ),
    # -------------------------------------------------------------- aggregate
    "aggregate_group_by": _x(
        """SELECT {sum_fk}, COUNT(*) AS n, SUM({sum_num}) AS total, AVG({sum_num}) AS mean
           FROM {sum_table} GROUP BY {sum_fk} ORDER BY {sum_fk}"""
    ),
    "aggregate_having": _x(
        """SELECT {sum_fk}, COUNT(*) AS n FROM {sum_table}
           GROUP BY {sum_fk} HAVING COUNT(*) > {n} ORDER BY {sum_fk}"""
    ),
    "aggregate_count_distinct": _x("SELECT COUNT(DISTINCT {fact_fk}) AS n FROM {fact}"),
    "aggregate_minmax": _x("SELECT MIN({fact_date}) AS lo, MAX({fact_date}) AS hi FROM {fact}"),
    "aggregate_rollup": _x(
        """SELECT {fact_status}, COUNT(*) AS n FROM {fact}
           GROUP BY ROLLUP({fact_status}) ORDER BY {fact_status}"""
    ),
    "aggregate_grouping_sets": _x(
        """SELECT {fact_status}, {fact_fk}, COUNT(*) AS n FROM {fact}
           GROUP BY GROUPING SETS (({fact_status}), ({fact_fk}))
           ORDER BY {fact_status}, {fact_fk}"""
    ),
    # ------------------------------------------------------------ string funcs
    "string_substr_instr": _x(
        """SELECT {dim_pk}, SUBSTR({dim_text}, 1, 3) AS s, STRPOS({dim_text}, 'a') AS i
           FROM {dim} ORDER BY {dim_pk}""",
        note="PostgreSQL has no INSTR; STRPOS is the two-argument equivalent.",
    ),
    "string_case_funcs": _x(
        """SELECT {dim_pk}, UPPER({dim_text}) AS u, LOWER({dim_text}) AS l,
                  INITCAP({dim_text}) AS c
           FROM {dim} ORDER BY {dim_pk}"""
    ),
    "string_pad_trim": _x(
        """SELECT {dim_pk}, LPAD({dim_text}, 20, '.') AS p, TRIM({dim_text}) AS t
           FROM {dim} ORDER BY {dim_pk}"""
    ),
    "string_replace": _x(
        "SELECT {dim_pk}, REPLACE({dim_text}, 'a', 'A') AS r FROM {dim} ORDER BY {dim_pk}"
    ),
    "string_regexp": _x(
        """SELECT {dim_pk}, REGEXP_SUBSTR({dim_text}, '[A-Za-z]+') AS word
           FROM {dim} WHERE REGEXP_LIKE({dim_text}, '^[A-Z]') ORDER BY {dim_pk}""",
        note="regexp_substr and regexp_like arrived in PostgreSQL 15, so they carry over.",
    ),
    "string_length_funcs": _x(
        """SELECT {dim_pk}, LENGTH({dim_text}) AS n FROM {dim}
           WHERE LENGTH({dim_text}) > {n} ORDER BY {dim_pk}"""
    ),
    # -------------------------------------------------------------------- DDL
    "ddl_table_basic": _x(
        """CREATE TABLE {obj0} (
             id          bigint          NOT NULL,
             label       varchar(60)     NOT NULL,
             amount      numeric(12,2),
             created_at  timestamp(0)    DEFAULT LOCALTIMESTAMP NOT NULL
           )"""
    ),
    "ddl_table_all_types": _x(
        """CREATE TABLE {obj0} (
             n_small     smallint,
             n_int       integer,
             n_big       bigint,
             n_dec       numeric(12,4),
             v_short     varchar(10),
             v_long      varchar(4000),
             c_fixed     char(3),
             d_date      timestamp(0),
             t_stamp     timestamp(6),
             big_text    text
           )"""
    ),
    "ddl_table_constraints": _x(
        """CREATE TABLE {obj0} (
             id      bigint          NOT NULL,
             code    varchar(20)     NOT NULL,
             state   varchar(10)     DEFAULT 'NEW' NOT NULL,
             qty     integer         NOT NULL,
             CONSTRAINT {obj0}_pk PRIMARY KEY (id),
             CONSTRAINT {obj0}_uq UNIQUE (code),
             CONSTRAINT {obj0}_ck CHECK (qty > 0),
             CONSTRAINT {obj0}_ck2 CHECK (state IN ('NEW', 'DONE'))
           )"""
    ),
    "ddl_table_composite_pk": _x(
        """CREATE TABLE {obj0} (
             parent_id   bigint      NOT NULL,
             line_no     smallint    NOT NULL,
             note        varchar(80),
             CONSTRAINT {obj0}_pk PRIMARY KEY (parent_id, line_no)
           )"""
    ),
    "ddl_table_fk": _x(
        """CREATE TABLE {obj0} (
             id          bigint  NOT NULL,
             ref_id      bigint,
             CONSTRAINT {obj0}_pk PRIMARY KEY (id),
             CONSTRAINT {obj0}_fk FOREIGN KEY (ref_id) REFERENCES {obj0} (id)
           )"""
    ),
    "ddl_index_single": _x(
        """CREATE TABLE {obj0} (id bigint, label varchar(40));
           CREATE INDEX {obj1} ON {obj0} (label)"""
    ),
    "ddl_index_composite": _x(
        """CREATE TABLE {obj0} (a bigint, b bigint, c timestamp(0));
           CREATE INDEX {obj1} ON {obj0} (a, b DESC)"""
    ),
    "ddl_sequence_basic": _x(
        "CREATE SEQUENCE {obj0} START WITH 1 INCREMENT BY 1 CACHE 1 NO CYCLE",
        note="NOCACHE becomes CACHE 1; NOCYCLE becomes NO CYCLE.",
    ),
    "ddl_sequence_options": _x(
        "CREATE SEQUENCE {obj0} START WITH 500 INCREMENT BY 10 MAXVALUE 100000 CACHE 20 CYCLE"
    ),
    "ddl_identity_always": _x(
        """CREATE TABLE {obj0} (
             id      bigint GENERATED ALWAYS AS IDENTITY,
             label   varchar(40) NOT NULL,
             CONSTRAINT {obj0}_pk PRIMARY KEY (id)
           )""",
        note="An unqualified NUMBER maps to numeric, but a PostgreSQL identity column "
        "must be an integer type, so bigint is used.",
    ),
    "ddl_identity_by_default": _x(
        """CREATE TABLE {obj0} (
             id      bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 5),
             label   varchar(40)
           )"""
    ),
    "ddl_view_simple": _x("CREATE VIEW {obj0} AS SELECT {fact_pk}, {fact_date} FROM {fact}"),
    "ddl_view_aggregate": _x(
        """CREATE VIEW {obj0} AS
           SELECT {fact_fk} AS k, COUNT(*) AS n FROM {fact} GROUP BY {fact_fk}"""
    ),
    "ddl_view_with_nvl": _x(
        """CREATE VIEW {obj0} AS
           SELECT {fact_pk}, COALESCE({fact_num_nullable}, 0) AS v FROM {fact}"""
    ),
    # -------------------------------------------------------------------- DML
    "dml_update_numeric": _x(
        """UPDATE {fact} SET {fact_num_nullable} = COALESCE({fact_num_nullable}, 0) + 1
           WHERE {fact_pk} <= 0"""
    ),
    "dml_update_all_matching": _x(
        """UPDATE {fact} SET {fact_status} = '{fact_status_value}'
           WHERE {fact_status} <> '{fact_status_value}'"""
    ),
    "dml_update_from_subquery": _x(
        """UPDATE {fact} SET {fact_date} = {fact_date} + INTERVAL '1 day'
           WHERE {fact_fk} IN (SELECT {dim_pk} FROM {dim} LIMIT 3)""",
        note="Adding 1 to an Oracle DATE adds a day; PostgreSQL needs an explicit interval.",
    ),
    "dml_delete_filtered": _x("DELETE FROM {fact} WHERE {fact_pk} < 0"),
    "dml_delete_subquery": _x(
        "DELETE FROM {fact} WHERE {fact_fk} NOT IN (SELECT {dim_pk} FROM {dim})"
    ),
    "dml_insert_select": _x(
        """INSERT INTO {fact} ({fact_pk}, {fact_fk}, {fact_date})
           SELECT {fact_pk} + 900000, {fact_fk}, {fact_date} FROM {fact} WHERE 1 = 0"""
    ),
    "merge_update_only": _x(
        """MERGE INTO {fact} t
           USING (SELECT {fact_pk} AS k FROM {fact} LIMIT 5) s
           ON (t.{fact_pk} = s.k)
           WHEN MATCHED THEN UPDATE SET {fact_date} = t.{fact_date}""",
        note="PostgreSQL gained MERGE in 15. The SET target is not table-qualified.",
    ),
    "merge_with_condition": _x(
        """MERGE INTO {fact} t
           USING (SELECT {dim_pk} AS k FROM {dim}) s
           ON (t.{fact_fk} = s.k)
           WHEN MATCHED AND t.{fact_pk} < 0 THEN UPDATE SET {fact_date} = t.{fact_date}""",
        note="Oracle filters with WHERE after UPDATE SET; PostgreSQL uses WHEN MATCHED AND.",
    ),
}
